import Header from "@/components/react/Header";
import {Inter} from "next/font/google";
import Head from "next/head";
import {useRouter} from 'next/router';
import {useBlogPostQuery} from "@/generated";

const inter = Inter({subsets: ["latin"]});

export default function Post() {
    const router = useRouter();
    const slug = (router.query.post as string[]) || [];
    const url = "/" + slug.join('/');
    const data = useBlogPostQuery({url: url}).data;
    const item = data?.LocationItemPage?.items[0];
    let image = item?.PageImage == undefined ? item?.Image?.Url : item?.PageImage?.Url;
    image = image == null ? `https://source.unsplash.com/random?city,landscape,${item?.Name.replace(' ','')}` : image;
    console.log(image);
    return (
        <>
            {item &&
                <>
                    <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app"/>
                        <meta name="viewport" content="width=device-width, initial-scale=1"/>
                        <link rel="icon" href="/favicon.ico"/>
                    </Head>
                    <Header height={15}/>
                    {/*<div className="flex flex-col justify-center">*/}
                    {/*  <div>*/}
                    {/*    <p className="text-2xl">Slug Page: {slug.join('/')}</p>*/}
                    {/*      <p>{data?.LocationItemPage?.items[0]?.Name}</p>*/}
                    {/*      <div dangerouslySetInnerHTML={{ __html: data?.LocationItemPage?.items[0]?.MainBody}} />*/}
                    {/*  </div>*/}
                    {/*</div>*/}
                    <div className="text-center pt-16 md:pt-32">
                        <p className="text-sm md:text-base text-green-500 font-bold">{item.StartPublish}</p>
                        <h1 className="font-bold break-normal text-3xl md:text-5xl">{item.Name}</h1>
                    </div>
                    <div className="container w-full max-w-6xl mx-auto bg-white bg-cover mt-8 rounded"
                         style={{backgroundImage: `url(${image})`, height: '30vh'}}></div>
                    <div className="container max-w-5xl mx-auto -mt-32">

                        <div className="mx-0 sm:mx-6">

                            <div
                                className="bg-white w-full p-8 md:p-24 text-xl md:text-2xl text-gray-800 leading-normal"
                                style={{fontFamily: 'Georgia,serif'}}>

                                <p className="text-2xl md:text-3xl mb-5">
                                    {item.MainIntro}
                                </p>

                                <div className="py-6" dangerouslySetInnerHTML={{__html: item.MainBody}}></div>


                            </div>

                            <div className="flex w-full items-center font-sans p-8 md:p-24">
                                <img className="w-10 h-10 rounded-full mr-4" src="http://i.pravatar.cc/300"
                                     alt="Avatar of Author"/>
                                <div className="flex-1">
                                    <p className="text-base font-bold text-base md:text-xl leading-none">Ghostwind
                                        CSS</p>
                                    <p className="text-gray-600 text-xs md:text-base">Tailwind CSS version of Ghost's
                                        Casper
                                        theme by <a
                                            className="text-gray-800 hover:text-green-500 no-underline border-b-2 border-green-500"
                                            href="https://www.tailwindtoolbox.com">TailwindToolbox.com</a></p>
                                </div>
                                <div className="justify-end">
                                    <button
                                        className="bg-transparent border border-gray-500 hover:border-green-500 text-xs text-gray-500 hover:text-green-500 font-bold py-2 px-4 rounded-full">Read
                                        More
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    )
                </>
            }</>
    );
}
